<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.20" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.12" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\BCP.Domain\BCP.Domain.csproj" />
  </ItemGroup>

</Project>
