/**
 * BilliardClubParisien.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserRequest } from '../model/models';
import { CreateUserResponse } from '../model/models';
import { LoginUserRequest } from '../model/models';
import { LoginUserResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param createUserRequest 
     */
    userCreate(createUserRequest: CreateUserRequest, extraHttpRequestParams?: any): Observable<CreateUserResponse>;

    /**
     * 
     * 
     * @param loginUserRequest 
     */
    userLogin(loginUserRequest: LoginUserRequest, extraHttpRequestParams?: any): Observable<LoginUserResponse>;

}
